# Generated by Django 6.1.1 on 2026-09-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('imagem_principal', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
