"""
Django settings for mbdryfit project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent


# Segurança
SECRET_KEY = 'django-insecure-lqr98+m74#c=qvwcwg6_qwbm0e_*e3c@yxzsac78hu1yw83l79'

DEBUG = True

ALLOWED_HOSTS = []


# Aplicativos

INSTALLED_APPS = [

    # Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


    # MB DRYFIT
    'clientes',
    'estoque',
    'etiquetas',
    'produtos',
    'usuarios',
    'vendedores',

]


MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]


ROOT_URLCONF = 'mbdryfit.urls'


TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

            ],

        },

    },

]


WSGI_APPLICATION = 'mbdryfit.wsgi.application'


# Banco de dados

DATABASES = {

    'default': {

        'ENGINE': 'django.db.backends.sqlite3',

        'NAME': BASE_DIR / 'db.sqlite3',

    }

}


# Senhas

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },

]


# Idioma

LANGUAGE_CODE = 'pt-br'


TIME_ZONE = 'America/Sao_Paulo'


USE_I18N = True


USE_TZ = True



# Arquivos estáticos

STATIC_URL = 'static/'


# Upload de imagens

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# Tipo padrão dos IDs

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'